/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Erick
 */

import Model.Gestion;
import Model.Estudiantes;
import java.util.Vector;


public class EntrarEstudiantes extends javax.swing.JDialog {


    public EntrarEstudiantes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        NombreEstudianteField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ApellidoEstudianteField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CIEstudianteField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        EdadEstudianteField = new javax.swing.JTextField();
        Registro = new javax.swing.JButton();
        Error = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setText("Nombre");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 89, 40));

        NombreEstudianteField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreEstudianteFieldActionPerformed(evt);
            }
        });
        jPanel2.add(NombreEstudianteField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 41));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel8.setText("Apellido");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 89, 40));

        ApellidoEstudianteField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoEstudianteFieldActionPerformed(evt);
            }
        });
        jPanel2.add(ApellidoEstudianteField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 150, 41));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setText("CI");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 89, 40));

        CIEstudianteField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CIEstudianteFieldActionPerformed(evt);
            }
        });
        jPanel2.add(CIEstudianteField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, 41));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setText("Edad");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 89, 40));

        EdadEstudianteField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadEstudianteFieldActionPerformed(evt);
            }
        });
        jPanel2.add(EdadEstudianteField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 150, 41));

        Registro.setBackground(new java.awt.Color(0, 0, 153));
        Registro.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Registro.setForeground(new java.awt.Color(255, 255, 255));
        Registro.setText("Registrar");
        Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroActionPerformed(evt);
            }
        });
        jPanel2.add(Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 130, 38));

        Error.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        Error.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(Error, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 250, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 19)); // NOI18N
        jLabel5.setText("Llene los Datos");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 370, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 440, 420));

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 60, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreEstudianteFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreEstudianteFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreEstudianteFieldActionPerformed

    private void ApellidoEstudianteFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoEstudianteFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoEstudianteFieldActionPerformed

    private void CIEstudianteFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CIEstudianteFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CIEstudianteFieldActionPerformed

    private void EdadEstudianteFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadEstudianteFieldActionPerformed
        // TODO add yourndling code here:
    }//GEN-LAST:event_EdadEstudianteFieldActionPerformed

    private void RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroActionPerformed
        // TODO add your handling code here:
        try{
            RevisarHuecos();
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_RegistroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
 public void RevisarHuecos() throws Exception{
        if(NombreEstudianteField.getText().isEmpty()||ApellidoEstudianteField.getText().isEmpty()||
                CIEstudianteField.getText().isEmpty()||EdadEstudianteField.getText().isEmpty()){
            Error.setText("Debe rellenar todos lo que se le pide");
        }
        else{
            Vector<Estudiantes> client = new Vector<Estudiantes>();
            try {
                client = Gestion.CargarDatos();	
            }
            catch(Exception ex) {
        	System.out.println("No hay datos");
            }
            
            try{
                String nombre = NombreEstudianteField.getText();
                String apellido = ApellidoEstudianteField.getText();
                String ci = CIEstudianteField.getText();               
                int edad = Integer.parseInt(EdadEstudianteField.getText());
            
                Estudiantes info = new Estudiantes(nombre,apellido,ci,edad);
            
                client = Gestion.Register_Client(info, client);
                
                Error.setText("");
                dispose();
            }
            catch(NumberFormatException x){
                Error.setText("Ha introducido letras en lugar de numeros");
            }
            catch(Exception x){
                Error.setText(x.getMessage());
            }
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntrarEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntrarEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntrarEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntrarEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EntrarEstudiantes dialog = new EntrarEstudiantes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoEstudianteField;
    private javax.swing.JTextField CIEstudianteField;
    private javax.swing.JTextField EdadEstudianteField;
    private javax.swing.JLabel Error;
    private javax.swing.JTextField NombreEstudianteField;
    private javax.swing.JButton Registro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
